[project]
name = "football_pool"
version = "2.0.0"
description = "A modern asynchronous FastAPI backend for tracking the results/history of the football pool."
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "alembic>=1.14.1",
    "asyncpg>=0.30.0",
    "better-profanity>=0.7.0",
    "fastapi>=0.115.11",
    "httpx>=0.28.1",
    "itsdangerous>=2.2.0",
    "psycopg[binary]>=3.2.5",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
    "pytz>=2025.2",
    "sqlalchemy[asyncio]>=2.0.38",
    "tzdata>=2025.2",
    "uvicorn[standard]>=0.34.0",
]

[dependency-groups]
dev = [
    "prek>=0.5.2",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
]

[tool.ruff]
line-length = 120
target-version = "py313"
include = ["apps", "migrations", "tests"]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # Pyflakes
    "I",   # isort
    "W",   # pycodestyle warnings
    "C90", # mccabe complexity
]
ignore = []

[tool.ruff.lint.mccabe]
max-complexity = 25

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"] # unused imports

[tool.uv]
default-groups = "all"
link-mode = "copy"
