"""Initial models addition.

Revision ID: 99c62c252caa
Revises:
Create Date: 2024-08-31 20:16:20.646407

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "99c62c252caa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "owners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(length=3), nullable=False),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("conference", sa.Enum("AFC", "NFC", name="conference"), nullable=False),
        sa.Column(
            "division", sa.Enum("NORTH", "SOUTH", "EAST", "WEST", name="division"), nullable=False
        ),
        sa.Column("wins", sa.Integer(), nullable=True),
        sa.Column("losses", sa.Integer(), nullable=True),
        sa.Column("ties", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("abbreviation"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("owner_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teams")
    op.drop_table("owners")
    # ### end Alembic commands ###
