"""Trying to fix relationship.

Revision ID: d51670f25756
Revises: 589935a87528
Create Date: 2025-08-23 01:25:12.828041

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d51670f25756"
down_revision = "589935a87528"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("owners", schema=None) as batch_op:
        batch_op.add_column(sa.Column("team_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "teams", ["team_id"], ["id"])

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("teams_owner_id_key"), type_="unique")
        batch_op.drop_constraint(batch_op.f("teams_owner_id_fkey"), type_="foreignkey")
        batch_op.drop_column("owner_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f("teams_owner_id_fkey"), "owners", ["owner_id"], ["id"])
        batch_op.create_unique_constraint(
            batch_op.f("teams_owner_id_key"), ["owner_id"], postgresql_nulls_not_distinct=False
        )

    with op.batch_alter_table("owners", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("team_id")

    # ### end Alembic commands ###
