"""Master data for all 32 NFL teams."""

from ..models.enums import Conference, Division

TEAMS_DATA = [
    # AFC East
    {
        "id": 1,
        "city": "Buffalo",
        "name": "Bills",
        "abbreviation": "BUF",
        "logo_url": "logos/buffalo-bills-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.EAST,
    },
    {
        "id": 2,
        "city": "Miami",
        "name": "Dolphins",
        "abbreviation": "MIA",
        "logo_url": "logos/miami-dolphins-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.EAST,
    },
    {
        "id": 3,
        "city": "New England",
        "name": "Patriots",
        "abbreviation": "NE",
        "logo_url": "logos/new-england-patriots-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.EAST,
    },
    {
        "id": 4,
        "city": "New York",
        "name": "Jets",
        "abbreviation": "NYJ",
        "logo_url": "logos/new-york-jets-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.EAST,
    },
    # AFC North
    {
        "id": 5,
        "city": "Baltimore",
        "name": "Ravens",
        "abbreviation": "BAL",
        "logo_url": "logos/baltimore-ravens-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.NORTH,
    },
    {
        "id": 6,
        "city": "Cincinnati",
        "name": "Bengals",
        "abbreviation": "CIN",
        "logo_url": "logos/cincinnati-bengals-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.NORTH,
    },
    {
        "id": 7,
        "city": "Cleveland",
        "name": "Browns",
        "abbreviation": "CLE",
        "logo_url": "logos/cleveland-browns-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.NORTH,
    },
    {
        "id": 8,
        "city": "Pittsburgh",
        "name": "Steelers",
        "abbreviation": "PIT",
        "logo_url": "logos/pittsburgh-steelers-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.NORTH,
    },
    # AFC South
    {
        "id": 9,
        "city": "Houston",
        "name": "Texans",
        "abbreviation": "HOU",
        "logo_url": "logos/houston-texans-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.SOUTH,
    },
    {
        "id": 10,
        "city": "Indianapolis",
        "name": "Colts",
        "abbreviation": "IND",
        "logo_url": "logos/indianapolis-colts-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.SOUTH,
    },
    {
        "id": 11,
        "city": "Jacksonville",
        "name": "Jaguars",
        "abbreviation": "JAX",
        "logo_url": "logos/jacksonville-jaguars-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.SOUTH,
    },
    {
        "id": 12,
        "city": "Tennessee",
        "name": "Titans",
        "abbreviation": "TEN",
        "logo_url": "logos/tennessee-titans-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.SOUTH,
    },
    # AFC West
    {
        "id": 13,
        "city": "Denver",
        "name": "Broncos",
        "abbreviation": "DEN",
        "logo_url": "logos/denver-broncos-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.WEST,
    },
    {
        "id": 14,
        "city": "Kansas City",
        "name": "Chiefs",
        "abbreviation": "KC",
        "logo_url": "logos/kansas-city-chiefs-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.WEST,
    },
    {
        "id": 15,
        "city": "Las Vegas",
        "name": "Raiders",
        "abbreviation": "LV",
        "logo_url": "logos/las-vegas-raiders-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.WEST,
    },
    {
        "id": 16,
        "city": "Los Angeles",
        "name": "Chargers",
        "abbreviation": "LAC",
        "logo_url": "logos/los-angeles-chargers-logo-transparent.png",
        "conference": Conference.AFC,
        "division": Division.WEST,
    },
    # NFC East
    {
        "id": 17,
        "city": "Dallas",
        "name": "Cowboys",
        "abbreviation": "DAL",
        "logo_url": "logos/dallas-cowboys-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.EAST,
    },
    {
        "id": 18,
        "city": "New York",
        "name": "Giants",
        "abbreviation": "NYG",
        "logo_url": "logos/new-york-giants-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.EAST,
    },
    {
        "id": 19,
        "city": "Philadelphia",
        "name": "Eagles",
        "abbreviation": "PHI",
        "logo_url": "logos/philadelphia-eagles-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.EAST,
    },
    {
        "id": 20,
        "city": "Washington",
        "name": "Commanders",
        "abbreviation": "WSH",
        "logo_url": "logos/washington-commanders-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.EAST,
    },
    # NFC North
    {
        "id": 21,
        "city": "Chicago",
        "name": "Bears",
        "abbreviation": "CHI",
        "logo_url": "logos/chicago-bears-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.NORTH,
    },
    {
        "id": 22,
        "city": "Detroit",
        "name": "Lions",
        "abbreviation": "DET",
        "logo_url": "logos/detroit-lions-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.NORTH,
    },
    {
        "id": 23,
        "city": "Green Bay",
        "name": "Packers",
        "abbreviation": "GB",
        "logo_url": "logos/green-bay-packers-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.NORTH,
    },
    {
        "id": 24,
        "city": "Minnesota",
        "name": "Vikings",
        "abbreviation": "MIN",
        "logo_url": "logos/minnesota-vikings-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.NORTH,
    },
    # NFC South
    {
        "id": 25,
        "city": "Atlanta",
        "name": "Falcons",
        "abbreviation": "ATL",
        "logo_url": "logos/atlanta-falcons-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.SOUTH,
    },
    {
        "id": 26,
        "city": "Carolina",
        "name": "Panthers",
        "abbreviation": "CAR",
        "logo_url": "logos/carolina-panthers-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.SOUTH,
    },
    {
        "id": 27,
        "city": "New Orleans",
        "name": "Saints",
        "abbreviation": "NO",
        "logo_url": "logos/new-orleans-saints-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.SOUTH,
    },
    {
        "id": 28,
        "city": "Tampa Bay",
        "name": "Buccaneers",
        "abbreviation": "TB",
        "logo_url": "logos/tampa-bay-buccaneers-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.SOUTH,
    },
    # NFC West
    {
        "id": 29,
        "city": "Arizona",
        "name": "Cardinals",
        "abbreviation": "ARI",
        "logo_url": "logos/arizona-cardinals-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.WEST,
    },
    {
        "id": 30,
        "city": "Los Angeles",
        "name": "Rams",
        "abbreviation": "LAR",
        "logo_url": "logos/los-angeles-rams-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.WEST,
    },
    {
        "id": 31,
        "city": "San Francisco",
        "name": "49ers",
        "abbreviation": "SF",
        "logo_url": "logos/san-francisco-49ers-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.WEST,
    },
    {
        "id": 32,
        "city": "Seattle",
        "name": "Seahawks",
        "abbreviation": "SEA",
        "logo_url": "logos/seattle-seahawks-logo-transparent.png",
        "conference": Conference.NFC,
        "division": Division.WEST,
    },
]
