"""Remove single parent stipulation.

Revision ID: 589935a87528
Revises: 6ae5ececcce6
Create Date: 2025-08-23 01:18:03.895601

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "589935a87528"
down_revision = "6ae5ececcce6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("owners", schema=None) as batch_op:
        batch_op.create_unique_constraint("owners_id", ["id"])

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_unique_constraint("teams_id", ["id"])

    with op.batch_alter_table("winning_games", schema=None) as batch_op:
        batch_op.create_unique_constraint("winning_games_id", ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("winning_games", schema=None) as batch_op:
        batch_op.drop_constraint("winning_games_id", type_="unique")

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_constraint("teams_id", type_="unique")

    with op.batch_alter_table("owners", schema=None) as batch_op:
        batch_op.drop_constraint("owners_id", type_="unique")

    # ### end Alembic commands ###
