"""Fixing foreign keys maybe lol

Revision ID: 6797067bbf7c
Revises: e622ce2b4945
Create Date: 2024-09-03 00:45:58.336953

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "6797067bbf7c"
down_revision = "e622ce2b4945"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("winning_games", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("winning_games", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
