"""Remove LE score for winning games.

Revision ID: a00cd32bb6e6
Revises: b577ca68ff41
Create Date: 2024-09-05 00:52:12.663493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00cd32bb6e6'
down_revision = 'b577ca68ff41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winning_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False))
        batch_op.drop_column('less_or_equal_score')
        batch_op.drop_column('more_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winning_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('more_score', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('less_or_equal_score', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('score')

    # ### end Alembic commands ###
