"""fixing round 3

Revision ID: b577ca68ff41
Revises: e829fbe103d9
Create Date: 2024-09-03 01:42:49.333292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b577ca68ff41'
down_revision = 'e829fbe103d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_constraint('owners_team_id_key', type_='unique')
        batch_op.drop_constraint('owners_team_id_fkey', type_='foreignkey')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('winning_games', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['team_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winning_games', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('owners_team_id_fkey', 'teams', ['team_id'], ['id'])
        batch_op.create_unique_constraint('owners_team_id_key', ['team_id'])

    # ### end Alembic commands ###
