"""Remove score

Revision ID: c0cb9bf1b6a9
Revises: a00cd32bb6e6
Create Date: 2024-09-05 01:57:01.665376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cb9bf1b6a9'
down_revision = 'a00cd32bb6e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winning_games', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winning_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
