"""Adding winning games to DB.

Revision ID: e622ce2b4945
Revises: 99c62c252caa
Create Date: 2024-09-03 00:23:37.563566

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e622ce2b4945"
down_revision = "99c62c252caa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "winning_games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("more_score", sa.Integer(), nullable=False),
        sa.Column("less_or_equal_score", sa.Integer(), nullable=False),
        sa.Column("winnings", sa.Integer(), nullable=False),
        sa.Column(
            "winning_type",
            sa.Enum("MOST", "LEAST", "FIFTY", "PLAYOFF", "SUPER_BOWL", name="winningtype"),
            nullable=False,
        ),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owners.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("owners", schema=None) as batch_op:
        batch_op.add_column(sa.Column("winnings", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("team_id", sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ["team_id"])
        batch_op.create_unique_constraint(None, ["id"])
        batch_op.create_foreign_key(None, "teams", ["team_id"], ["id"])

    with op.batch_alter_table("owners", schema=None) as batch_op:
        batch_op.execute("UPDATE owners SET winnings = 0")
        batch_op.alter_column("winnings", nullable=False)

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("owners", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("team_id")
        batch_op.drop_column("winnings")

    op.drop_table("winning_games")
    # ### end Alembic commands ###
