secrets:
  flask_secret_key:
    file: ${SECRETS_DIR}/football_pool_local_flask_secret_key
  db_user:
    file: ${SECRETS_DIR}/football_pool_local_db_user
  db_pass:
    file: ${SECRETS_DIR}/football_pool_local_db_password

services:
  devcontainer:
    build:
      args:
        IMAGE_NAME: ubuntu
        IMAGE_TAG: 24.04
      context: ${GIT_REPOS_DIR}/football-pool
      dockerfile: ./.devcontainer/devcontainer.dockerfile
    volumes:
      - ${GIT_REPOS_DIR}/football-pool:/workspace
    secrets:
      - flask_secret_key
      - db_user
      - db_pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  football-pool-db:
    image: postgres:17
    container_name: football-pool-postgres-local
    hostname: football-pool-postgres-local
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "pg_isready -q -d football-pool -U $(cat /run/secrets/db_user)",
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - football-pool-localdb:/var/lib/postgresql/data:rw
    secrets:
      - flask_secret_key
      - db_user
      - db_pass
    environment:
      POSTGRES_DB: football-pool
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    restart: on-failure:5

volumes:
  football-pool-localdb:
